name: Docker Image CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login DockerHub
        run: docker login -u Kbamunuarachchi0331 -p ,'$Y4^a#3.YZ;s>AY'
      - name: Build the Docker image
        run: docker build -t coursework-group_95:latest .
      - name: Push to DockerHub
        run: docker push Kbamunuarachchi0331/coursework-group_95:latest
